services:
  site:
    image: felipegasp/tagtech-nodejs:latest
    ports:
      - "3333:3333"
    networks:
      - rede-compose
    depends_on:
      - db

  db:
    image: felipegasp/tagtech-db:latest
    environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - rede-compose

networks:
  rede-compose:
    driver: bridge

